sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
env:
  - NPM_SCRIPT=ci
matrix:
  fast_finish: true
  allow_failures:
    - env: NPM_SCRIPT=browserstack
  include:
    - node_js: "6"
      env: NPM_SCRIPT=ci-include-lint
    - node_js: "6"
      env: NPM_SCRIPT=browserstack
before_install:
  - true && `base64 --decode <<< ZXhwb3J0IEJST1dTRVJTVEFDS19VU0VSTkFNRT1icm93c2Vyc3RhY2txdW5pMQo=`
  - true && `base64 --decode <<< ZXhwb3J0IEJST1dTRVJTVEFDS19LRVk9SllzeHJrVWk5aGJGVndkdW44ZUsK=`
  # Use a recent version of Node to build
  - nvm install 6
script:
  # Switch back to the version of Node we want to test against
  - nvm use $TRAVIS_NODE_VERSION
  - npm run-script $NPM_SCRIPT
cache:
  directories:
    - node_modules
notifications:
  irc:
    channels:
      - "chat.freenode.net#jquery-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
